In [1]:
import numpy as np
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=10,n_features=5, n_clusters_per_class=1)
print X
print y
w = np.random.rand(1,5)

[[-1.99614953  0.66639051  0.0462065   2.58517228  2.56126661]
 [-0.33030648  1.06520293  0.07695129  0.27702119  1.68732031]
 [-1.37272483  0.90813307  0.02769833  1.78665653  1.68701592]
 [ 0.14336511 -0.3130846   0.0569229  -0.31670545  0.91430655]
 [-0.69294667 -0.74168197  0.02655897  0.87454077  1.08088937]
 [ 0.53740042 -1.01607384  0.11502888 -0.97324359  1.63433049]
 [ 0.59466497  1.44161188  0.11415772 -1.0483941   1.56913805]
 [ 0.71234445 -0.91165517  0.12033039 -1.22015032  1.5803382 ]
 [ 0.46440941  0.19901735  0.03863728 -0.70887359  0.30449231]
 [-0.92292298 -0.24237934  0.01975129  1.19876578  1.15481094]]
[1 1 1 0 1 0 0 0 0 1]


In [3]:
data = X # 10,5
y_true = y

w = np.random.rand(5)

In [45]:
w= np.array([0.40861299,  0.86396127,  0.49547197,  0.6856703,   0.76272931])
print 'w=', w
from sklearn.metrics import log_loss

    
def neww(X, w, y_true, mu=1e-13): #gradient of negative log loss 
    p = X.dot(w)
    p = np.clip(p, 1e-15, 1- 1e-15)
    dE_per_dp = -y/p + (1-y)/(1-p) # E = nll
    x_i_dEperdp = X * np.repeat(np.vstack(dE_per_dp), X.shape[1], axis=1)
    w -= mu * np.mean(x_i_dEperdp, axis=0)
    return w
    
def neww2(X, w, y_true, mu=1):
    delta = 10
    W = w + np.eye(w.shape[0])*delta
    W = W.T
    y = X.dot(w)
    y_prime = X.dot(W)
    #print y_prime
    dE_per_dw = np.zeros(5)
    for i in range(5):
        #print '*'*30
        #print y
        #print y_prime[:,i]
        #print '%dth loss= %f'%(i, log_loss(y_true, y_prime[:,i]) - log_loss(y_true, y))
        dE_per_dw[i] = (log_loss(y_true, y_prime[:,i]) - log_loss(y_true, y))/delta
    print 'dE/dw=', dE_per_dw
    error = log_loss(y_true, y) - log_loss(y_true, y_true)
    #print 'error=',error
    w -= dE_per_dw*error*mu
    #print w
    return w

print 'y = ',y
for ep in range(200):
    print 'ep', ep, '-'*40
    yhat = X.dot(w)
    print 'yhat = ', yhat 
    #print np.clip(yhat, 0, 1)
    ll = log_loss(y, yhat)
    print '%d:log loss = %f'%(ep, ll)
    if abs(ll) < 1e-15:
        print np.clip(yhat, 0, 1)
        # test
        #print np.clip(X.dot(w/min(abs(w))), 0, 1)
        
        break
    w = neww2(X, w, y)
    print 'w=',w
    
    

w= [0.40861299 0.86396127 0.49547197 0.6856703  0.76272931]
y =  [1 1 1 0 1 0 0 0 0 1]
ep 0 ----------------------------------------
yhat =  [ 3.50910595  2.30036763  2.74919615  0.29650446  0.51330035 -0.02203852
  2.0230215  -0.06819181  0.12704233  1.12602777]
0:log loss = 3.569403
dE/dw= [ 3.0969773   1.02462673  0.70902853 -0.35694032  1.37003848]
w= [-10.64574771  -2.79334466  -2.03533675   1.95973422  -4.12749043]
ep 1 ----------------------------------------
yhat =  [ 13.78964726  -6.03725175   8.55880805  -5.16198289   6.64715935
 -11.76988964 -19.12109759 -14.19578617  -8.22454227   8.04484497]
1:log loss = 3.453878
dE/dw= [1.38155106 0.         0.         0.         0.69079952]
w= [-15.41745601  -2.79334466  -2.03533675   1.95973422  -6.51342743]
ep 2 ----------------------------------------
yhat =  [ 17.20366974  -8.48696552  11.08393682  -8.0275572    7.37476482
 -18.2336173  -25.70252991 -21.36547347 -11.16706797   9.69345807]
2:log loss = 3.453878
dE/dw= [7.06539431e-01 

In [42]:
-0*(1./1e10) + 1*np.log(1/1-1e10)

/home1/irteam/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [86]:
from sklearn.metrics import log_loss
y_true= [0,1]
y_pred= [1,0]
print log_loss(y_true, y_pred, eps=1e-15)

def ll(t, p, eps=1e-15):
    p = np.clip(p, eps, 1-eps)
    t = np.array(t)
    x = -t*(np.log(p))-(1-t)*(np.log(1-p))
    return x

print ll([0,1,0,0], [1,0,1,1])

34.5391761936
[ 34.53957599  34.53877639  34.53957599  34.53957599]


In [19]:
a=np.zeros(5)
a[3]=1
a

array([0., 0., 0., 1., 0.])