http://scikit-learn.org/stable/modules/preprocessing.html

# scale

In [5]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
X_scaled = preprocessing.scale(X_train) # column base standardization

X_scaled  

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

# one hot encoder

In [3]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])  


enc.n_values_,enc.feature_indices_,enc.transform([[0, 1, 1]]).toarray()

(array([2, 3, 4]),
 array([0, 2, 5, 9]),
 array([[ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.]]))

refer https://stackoverflow.com/questions/42728772/explain-onehotencoder-using-python
    

# polynomial features

from $(X_1, X_2)$ to $(1, X_1, X_2, X_1^2, X_1 X_2, X_2^2)$

In [11]:
X = np.arange(6).reshape(3,-1)
print X
p2 = preprocessing.PolynomialFeatures(2)
p2.fit_transform(X)

[[0 1]
 [2 3]
 [4 5]]


array([[  1.,   0.,   1.,   0.,   0.,   1.],
       [  1.,   2.,   3.,   4.,   6.,   9.],
       [  1.,   4.,   5.,  16.,  20.,  25.]])

from $(X_1, X_2, X_3)$ to $(1, X_1, X_2, X_3, X_1X_2, X_1X_3, X_2X_3, X_1X_2X_3)$

In [15]:
X = np.arange(9).reshape(3,-1)
p3 = preprocessing.PolynomialFeatures(degree=3, interaction_only=True)
X, p3.fit_transform(X)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[   1.,    0.,    1.,    2.,    0.,    0.,    2.,    0.],
        [   1.,    3.,    4.,    5.,   12.,   15.,   20.,   60.],
        [   1.,    6.,    7.,    8.,   42.,   48.,   56.,  336.]]))

# Custom trnasformers

like `map` function 

In [16]:
t = preprocessing.FunctionTransformer(np.log1p) # log(1+x)
t.transform([[0,1],[2,3]])

array([[ 0.        ,  0.69314718],
       [ 1.09861229,  1.38629436]])